name: Build Nyxgine

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install GLFW
        run: |
          curl -L https://github.com/glfw/glfw/releases/download/3.4/glfw-3.4.bin.WIN64.zip -o glfw.zip
          unzip glfw.zip
      
      - name: Compile
        run: |
          gcc libs/glad.c src/game/main.c src/math/vec3.c src/math/mat4.c src/math/quat.c src/core/window.c src/core/input.c src/core/time.c src/render/shader.c src/render/mesh.c src/render/camera.c src/physics/rigidbody.c -I glfw-3.4.bin.WIN64/include -I libs -I src/math -I src/core -I src/render -I src/physics -L glfw-3.4.bin.WIN64/lib-mingw-w64 -lglfw3 -lopengl32 -lgdi32 -lm -o nyxgine.exe
      
      - uses: actions/upload-artifact@v4
        with:
          name: nyxgine
          path: nyxgine.exe
